[workspace]
name = "AMMR"
authors = ["AnyBody Technology <sales@anybodytech.com>"]
homepage = "http://anybodytech.com"
repository = "https://githubcom/anybody/ammr"
documentation = "https://anyscript.org/ammr"
channels = ["conda-forge", "anybody"]
platforms = ["win-64"]
description = """
    Python environment for running python tools with the AMMR.
    See https://pixi.sh for more information.
"""


[dependencies]
python = ">=3.13.0,<3.14"
anypytools = ">=1.20.3,<2"


# It is possible to add a particualar version of the AnyBody console 
# application here, so that AnyPyTools will always run with this version.
#
# anybodycon=="8.1.4" 
#
# When using a anybodycon from pixi, then we also need to explicitly tell anybodycon
# where to find suitlable python environment, if the model uses any Python hooks.
#
# [activation]
# env = { ANYBODY_PYTHON_HOME = "$PIXI_PROJECT_ROOT/.pixi/envs/default" }