name: sphinx2
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - sphinx
  - make
  - myst-parser
  - pygments_anyscript
  - matplotlib
  - pillow
  - jinja2
  - sphinx-book-theme
  - sphinx-design
  - tomli
  - pyYAML
  - pip:
    - sphinxext-opengraph
    - python-frontmatter
